export const REGISTER_USER = 'REGISTER_USER';
export const USER_LOGIN_START         =  'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const LOGIN = 'LOGIN';
export const LOGOUT         =  'LOGOUT';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const TodoList_START = 'TodoList_START';
export const TodoList_SUCCESS = 'TodoList_SUCCESS';
export const TodoList_FAIL = 'TodoList_FAIL';
export const TODO_CREATE_START = 'TODO_CREATE_START';
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const DATA_OPERATION = 'DATA_OPERATION';
export const TODO_SINGLE_FETCH_START = 'TODO_SINGLE_FETCH_START';
export const TODO_SINGLE_FETCH_FAIL = 'TODO_SINGLE_FETCH_FAIL';
export const TODO_SINGLE_FETCH_SUCCESS = 'TODO_SINGLE_FETCH_SUCCESS';




